[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = []

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "deny"

[licenses]
confidence-threshold = 0.8
allow = ["MIT", "Apache-2.0", "Zlib", "Unicode-3.0"]

[sources]
unknown-registry = "warn"
